name = "cookie-care-joy"
type = "service"
main = "src/index.js"
compatibility_date = "2025-04-17"

# ── KV Namespace ──────────────────────────────────────────────────────────────
# This stores Web Push subscriptions
[[kv_namespaces]]
binding = "CCJ_SUBS"
id = "28f2e2c698e64cd5be42dd23a748a513"

# ── Scheduled Trigger (Cron) ───────────────────────────────────────────────────
# Runs every 30 minutes to send motivational push notifications
[triggers]
crons = ["*/30 * * * *"]
